import { expect, test } from "@playwright/test"

// Landing page (index.html) — its asset grid and hero card are generated by
// src/landing.ts from the SAME config as the dApp, so the marketing page can
// never claim a different lineup than app.html actually offers.

// Live tiles render as links whose aria-label is "<code> — <name>. Open in
// the Authline app." (the explicit label set by landing.ts).
const LIVE_CODES = ["USDC", "EURCV", "EURC", "BLND", "TLO"]

test("asset grid mirrors the dApp directory and live tiles deep-link into the app", async ({
	page,
}) => {
	await page.goto("/index.html")
	// Registry-pinned testnet assets render as LIVE links (the old static page
	// hardcoded USDC/EURC as "Coming soon").
	for (const code of LIVE_CODES) {
		const card = page.getByRole("link", {
			name: new RegExp(`^${code} — .*Open in the Authline app`),
		})
		await expect(card).toHaveCount(1)
		await expect(card).toHaveAttribute(
			"href",
			new RegExp(`app\\.html\\?asset=${code}$`),
		)
	}
	// Roadmap-only assets stay "Coming soon" and are not links.
	await expect(page.getByText("BENJI", { exact: true })).toBeVisible()
	await expect(page.getByRole("link", { name: /BENJI/ })).toHaveCount(0)

	// The hero card's network label comes from config, never a hardcoded claim.
	await expect(
		page.getByText("Stellar · Testnet", { exact: true }),
	).toBeVisible()

	// Clicking a live tile lands on the dApp with that asset preselected.
	await page.getByRole("link", { name: /^EURCV — / }).click()
	await page.waitForURL(/app\.html\?asset=EURCV/)
	await expect(
		page.getByRole("button", { name: /Connect wallet/i }),
	).toBeVisible()
})

test("hero Activate button opens the dApp instead of fake-authorizing in place", async ({
	page,
}) => {
	await page.goto("/index.html")
	await page.getByRole("button", { name: /^Activate / }).click()
	// Old behavior: an in-place "Authorized and ready to receive" animation
	// with no on-chain effect. New behavior: go do the real thing.
	await page.waitForURL(/app\.html\?asset=/)
	await expect(
		page.getByRole("button", { name: /Connect wallet/i }),
	).toBeVisible()
})
